# Generated by Django 4.2 on 2023-04-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=50)),
                ('categoria_pregunta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Encuestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('DNI', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('localidad_de_nacimiento', models.CharField(max_length=50)),
                ('localidad_de_residencia', models.CharField(max_length=50)),
                ('nivel_educativo', models.CharField(max_length=50)),
                ('profesion_u_oficio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=50)),
            ],
        ),
    ]
